[project]
name = "fast_string_replace"
version = "0.1.0"
description = "Efficient multi-location string replacement in Python using a C backend."
authors = [
    { name="Ariel Erijman", email="aerijman@fredhutch.org" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.6"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
